### ISSUE TITLE
TypeError: window.getComputedStyle is not a function

### ISSUE THREAD

**Issue by sherry9872** [DevExpress/devextreme-angular#1177]
# Bug Report

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join('.', 'browser', 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;
global['Event'] = win.Event;
global['CSS'] = null;
 The above code in serevr.ts for SSR breaks the build

**Package versions:**

    devexteme version: 20.2.6
    devextreme-angular version: 20.2.6

**Steps to reproduce:**

**Current behavior:**

The SSR build fails with below error on using domino
TypeError: window.getComputedStyle is not a function
**Expected behavior:**

The SSR build should work.
**Screenshots:**

**Comment by LexDX** [comment]
Hi @sherry9872,

At the moment, it is unclear how to reproduce the issue on our side. Please create a sample project to show the issue and specify the steps to reproduce it, so that we can analyze and debug it on our side. Feel free to reopen the issue once the project is ready. We will research it on our side.
