### ISSUE TITLE
dx-gallery is not working

### ISSUE THREAD

**Issue by Laoujin** [DevExpress/devextreme-angular#214]
Simple Plunker: does not allow one to switch pictures:
http://plnkr.co/edit/W5merLg4XC3TMqXWRGC2?p=preview

- The Left/Right navigation links and navigation circles: Do not do anything when clicked
- The Left/Right buttons: One right press does make the Left/Right buttons visible but the first image is always being displayed
- There is no example for how to use dx-gallery
- Need to explicitly set the height for the gallery div wrapper (but I guess that's just one of those css things?) Is quite confusing that you can set the width/height for the gallery which does nothing if the div above does not have at least that width/height though

**Comment by dxbykov** [comment]
Hi,

I've modified your sample. Please check [this plunker](http://plnkr.co/edit/sAGq7NYvVgUFhg5Cgqur?p=preview).

Your getPictureUrls method is invoked each time Angular needs to detect changes. And it does it on any DOM event. Due to the implementation, each call instantiates a new array of images and the widget has to re-render it. Your array is static. You need to create it once and return the ready array from the method.

**Comment by stevenrobijns** [comment]
This indeed works for us. Thanks.
