### ISSUE TITLE
DxActionSheet - The dxi-item option doesn't work correctly

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-angular#225]
The DevExtreme Angular package version is 16.2.1-alpha.3

See an [example](http://plnkr.co/edit/Qu4UD7?p=preview)

**Comment by dxbykov** [comment]
This behavior is by design. Since you are using the `dxi-item` configuration components to specify the action sheet items, their content is considered as a template. That's why only text is rendered. If you'd like buttons to be rendered instead of text, you have two options:

- Since your items are static, you can [specify them via the 'items' attribute](http://plnkr.co/edit/Vdk8Vc?p=preview).
- You can [use the 'dx-button' components inside the 'dxi-item' component](http://plnkr.co/edit/yTFrNt?p=preview) as a template.
