### ISSUE TITLE
dx-data-grid: scrolling mode="virtual" not working (16.2.1-alpha.3)

### ISSUE THREAD

**Issue by fdcastel** [DevExpress/devextreme-angular#234]
After upgrading to 16.2 I can't use virtual mode anymore. The `totalCount()` method from my `CustomStore `is never called.

### Template:
```html
<dx-data-grid [dataSource]="gridDataStore" style="display: block">
    <dxo-editing [allowUpdating]="true" [allowAdding]="false" [allowDeleting]="false" mode="cell"></dxo-editing>
    <dxo-load-panel [enabled]="false"></dxo-load-panel>
    <dxo-scrolling mode="virtual" [preloadEnabled]="true" showScrollbar="always"></dxo-scrolling>
    <dxo-sorting mode="none"></dxo-sorting>
</dx-data-grid>
```

### Code:
```javascript
  public gridDataStore = new CustomStore({

    load: (options) => {
      // This is called
      console.log('load', options);
      return new Promise((resolve, reject) => {
        resolve([{ text: 'Test 1' }, { text: 'Test 2' }, { text: 'Test 3' }]);
      });
    },

    totalCount: (options) => {
      // This is NEVER called (!?) -- Works in 16.1
      console.log('totalCount');
      return new Promise((resolve, reject) => {
        resolve(30);
      });
    }
  });
```

While I'm using [configuration components](https://github.com/DevExpress/devextreme-angular#advanced-devextreme-widget-options-configuration) (a feature from 16.2) in this sample the problem occurs even when not using them. E.g.:

```html
<dx-data-grid 
  [dataSource]="gridDataStore"
  [scrolling]="{
    mode: 'virtual',
    preloadEnabled: true,
    showScrollbar: 'always' }"
   ...
</dx-data-grid>
```

In 16.1 this code works. (`totalCount` is called)
In 16.2 this code don't work. (`totalCount` is never called)

Please see the attached sample. 
[gh-234.zip](https://github.com/DevExpress/devextreme-angular/files/601209/gh-234.zip)

**Comment by dxvladislavvolkov** [comment]
Hello!
This behavior takes places due to a Breaking Change we introduced in v16.2 and is considered to be by design now. Please refer to the [BC3882 - "dxDataGrid - The "remoteOperations" default value for CustomStore has been changed"](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme+(HTML+JS)&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=BreakingChanges&StartBuildName=16.2.2&EndBuildName=16.2.2&version-mode=single-mode) thread for details. 
Note that you can see a workaround method for your example [here](http://plnkr.co/edit/008u39Dovp3zCPRYQZOS?p=preview). I hope this helps.
