### ISSUE TITLE
Globalization + Angular-CLI

### ISSUE THREAD

**Issue by Laoujin** [DevExpress/devextreme-angular#297]
How to globalize the Devextreme widgets with Angular-CLI?

The following does not work when executing the instructions from the readme to load the examples locally (webpack crash)
https://github.com/DevExpress/devextreme-examples/tree/16_2/webpack-angular-globalize

Instructions found on the DevExtreme documentation sites use Knockout or jQuery.
Instructions from Globalize readme itself do not work.

Is https://github.com/DevExpress/DevExtreme-Intl the way to go? Will it work with Angular2 + Angular-CLI?

**Comment by Laoujin** [comment]
Most important for us is to indicate the start of the week as Monday instead of Sunday.
Would this be the case if we manage to set the `Globalize.localte('nl')`?

**Comment by DokaRus** [comment]
Hi,
We're planning to add an example that demonstrates how you can create an application via [angular-cli](https://github.com/angular/angular-cli) using devextreme-angular with localization and [devextreme-intl](https://github.com/DevExpress/DevExtreme-Intl) soon. I'll update this issue when we publish it

**Comment by DokaRus** [comment]
We have published [an example](https://github.com/DevExpress/devextreme-examples/tree/16_2/intl-angular) that demonstrates how you can create an angular application using [angular-cli](https://github.com/angular/angular-cli) devextreme-angular and devextreme-intl.
Feel free to ask if you will need further assistance.

**Comment by halcharger** [comment]
I have a similar requirement to the above. I'm using Angular2 + angualr-cli + DevExtreme but I need to change the default currency symbol from USD ($) to ZAR (R). 

According to DevExtreme documentation (https://js.devexpress.com/Documentation/16_1/Guide/Common/Migrate_to_the_New_Version/#Common_Migrate_to_the_New_Version_161_Version_Specifics_Localization) devextreme does not require Globalization UNLESS you require a currency other than USD. 

This leaves me in the position where I'm using angular2 + angular-cli + devextreme and now I need to add globalization but you don't seem to support this scenario because I believe that angular-cli projects don't expose the webpack config file and using globalization with and angular-cli project requires a change to the webpack config file?

What am I to do?

**Comment by llusetti** [comment]
I've found out you can change the currency symbol this way:
`import config from 'devextreme/core/config';
config({ defaultCurrency: 'EUR' });`
