### ISSUE TITLE
devextreme-angular with Dart

### ISSUE THREAD

**Issue by Severanin** [DevExpress/devextreme-angular#355]
Can I use devextreme-angular with Dart?
Thank you advance!

**Comment by ovchinnikov** [comment]
Hello,
We don't have special support for Dart. As far as I know, there are libraries that can compile Dart code based on TypeScript types definition files (https://github.com/angular/ts2dart). I can only suggest you try to use them so that you can integrate our components into your Angular application written in Dart. But, I personally didn't test this approach.
