### ISSUE TITLE
DataGrid: Focus on selection

### ISSUE THREAD

**Issue by Faey2222** [DevExpress/devextreme-angular#368]
DevExpress Version: devextreme-angular@^16.2.3-rc.3

I'm developing a Asset-Management Component for "Froala-Editor". Everything works fine and as expected but unfortunately after selecting a File (using DataGrid) my focus in the Editor get lost. After some reading I figured out, that DataGrid sets the focus to the selected row.

Is there any way I can use the DataGrid without the loss of the focus on my editor?

**Comment by GoshaFighten** [comment]
To be honest, this issue looks related to our dxDataGrid widget rather than to our Angular integration. Then, it's not quite clear what you mean by "selecting a File". Are you rendering dxFileUploader in a grid cell? I suggest you open a Support Center ticket along with a sample project to reproduce the issue so that we can see it in action.
