### ISSUE TITLE
Suggestion : Get dx-validation-summary to work with angular form validation

### ISSUE THREAD

**Issue by RonaldV** [DevExpress/devextreme-angular#380]
devextreme-angular version 16.2.4

See example https://github.com/DevExpress/devextreme-angular#angular-forms

It would be nice to have the same functionality when using dx-validation-summary with angular form validation instead of DevExtreme Validation Features.

**Comment by alc86** [comment]
Hi,
I tried it with the descriped solution but this does not work. Cloud you please create a working example on plunker ?

**Comment by artem-kurchenko** [comment]
Hi all,

We've double-checked this request and decided to close it.
The current implementation of ValidationSummary is not specific to a particular platform and is designed to work with our [built-in validation](https://js.devexpress.com/Documentation/Guide/Angular_Components/Component_Configuration_Syntax/#DevExtreme_Validation_Features). For Angular-specific features, we recommend using standard Angular approaches to display validation summary because our editors fully support Angular Forms: [DevExtreme - Angular Forms Support](https://js.devexpress.com/Documentation/Guide/Angular_Components/Component_Configuration_Syntax/#Angular_Forms_Support)
