### ISSUE TITLE
dxTextBox two way binding using ngModel does not function as expected

### ISSUE THREAD

**Issue by cfsean** [DevExpress/devextreme-angular#405]
devexteme version: 16.2
    devextreme-angular version: 16.2

[ x] bug Report 
Please see this plunk. Why is the text for the dxTextBox not set from the value defined in ngAfterViewInit?
http://plnkr.co/edit/3aiMm0utIprWTjnrqOWA?p=preview

Things to note:
Does not happen using one way binding on the dx-text-box
Also occurs on a dx-select-box

**Comment by alexzuza** [comment]
Angular uses unidirection data flow. Your code is executed after view checking. And in the second checking(angular is firing it in dev mode) you will get inconsistent data. If you open console then you can see the error:

> Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'DevExtreme button!'.

You should not change value within `ngAfterViewInit` hook otherwise you have to fire the change detection cycle via setTimeout or cdRef.detectChanges()

See result here http://plnkr.co/edit/KQJxm7jI8WUx90aGC5oS?p=preview

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
