### ISSUE TITLE
dx-accordion template and binding with ngModel

### ISSUE THREAD

**Issue by luigidallavalle** [DevExpress/devextreme-angular#439]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2.6
    devextreme-angular version: 16.2.6 
- Specify the type of the issue (check one with "x"): 
[ X]bug Report 
[ ] feature request 
[ ] support inquiry 

I'm experiencing the following error 
"Unhandled Promise rejection: Cannot assign to a reference or variable! ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot assign to a reference or variable!"
if, in an accordion template, I use the variable that represent a datasource-item, as ngModel target for another component. The following code throws the above error:
    
    <dx-accordion [dataSource]="data">
      <div *dxTemplate="let i of 'title'" >
        header of {{i.prop}}
      </div>
      <div *dxTemplate="let i of 'item'">
        <my-item [(ngModel)]="i"></my-item>
      </div>
    </dx-accordion>

Here's a plunker to reproduce the issue: 
http://plnkr.co/edit/g0wFRo3JBOxID1rYherT?p=preview

Is there something that I missed out ?

**Comment by SvetlanaRebrova** [comment]
Hello,

We have thoroughly examined your scenario and found that this error is not directly related to our dxAccordion. It can be reproduced when your component is placed in a <div> element with *ngFor and the resulting item is used in the ngModel binding. Please refer to the [example](http://plnkr.co/edit/HneaGJgWNjLcY4dOeHlN?p=preview) where I demonstrated this scenario. Note that our dxAccordion uses *ngFor to display items. Therefore, the same issue occurs in this component.
A similar problem was discussed in the [Bind array from a json object to a form using ngModel in Angular2](http://stackoverflow.com/questions/40852107/bind-array-from-a-json-object-to-a-form-using-ngmodel-in-angular2). It seems to be related to Angular specificity and occurs when an item obtained from *ngFor is passed to the ngModel binding.
As a possible workaround, I recommend you pass only the required property of your data object to the ngModel binding instead of the whole item:
`<div *dxTemplate="let i of 'item'">
    <my-item [(ngModel)]="i.prop"></my-item>`
As an alternative approach, you can obtain the corresponding object from your data array based on the current item values and pass it in the ngModel expression. See the [example](http://plnkr.co/edit/602ISCCTK1WReFq97Tv9?p=preview) where I illustrated this approach.

**Comment by luigidallavalle** [comment]
@SvetlanaRebrova, thanks for your answer and for the examples provided. It's now clear that it's not a devextreme issue.
