### ISSUE TITLE
dx-data-grid/dxi-column allowEditing has no effect

### ISSUE THREAD

**Issue by joerggross** [DevExpress/devextreme-angular#441]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version:  16.2.4
    devextreme-angular version:  16.2.4
- Specify the type of the issue (check one with "x"): 
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Using form editing mode in a dxi-data-grid the dxi-column/allowEditing option has no effect, the item is still editable:

`

    <dx-data-grid 
        id="gridContainer"
        [dataSource]="source"
        >
        <dxo-editing 
            mode="form"
            [allowUpdating]="true"
           >
        </dxo-editing>
        <dxi-column dataField="id" allowEditing="false"></dxi-column>
        <dxi-column dataField="city" ></dxi-column>
        <dxo-load-panel [enabled]="true"></dxo-load-panel>
    </dx-data-grid>
`

**Comment by SvetlanaRebrova** [comment]
Hello,

I've created a Plunker sample project based on this scenario but haven't managed to reproduce this issue. See the [Plunker sample](http://plnkr.co/edit/6PRVEzUQo4eTqTc4mRFN?p=preview). As you can see, it's not possible to change the value of the "ID" column's editor on the edit form when its allowEditing property is set to false. Would you please clarify if you can reproduce the problem in this sample? Otherwise, modify it according to your scenario and send us a video of the issue.

**Comment by joerggross** [comment]
Hi,
using the square brackets for the [allowEditing] property it works!
Thanks!
