### ISSUE TITLE
DxSelectBox doesn't use a default empty item if  searchEnabled is true and value & display text are blank

### ISSUE THREAD

**Issue by bstodola-lhi** [DevExpress/devextreme-angular#461]
devexteme version: 16.2.6
    devextreme-angular version: 16.2.4 

[x ] bug Report 

Demonstration: http://plnkr.co/edit/ruAC5M?p=preview

Hello, In our application, we would like to allow users to search for items in the select using the keyboard, The items list contains '' as one of the options, so that if the user clears the value from the select it should update the model to '', rather than having a descriptive item like 'Blank' or 'N/A'.  I would expect the model property to be updated to the empty string.  Instead, the property is set to null when the control loses focus. 

Any feedback would be greatly appreciated. 
Thanks, Brian

**Comment by bstodola-lhi** [comment]
Hello, I did some digging and found a workaround to get the expected behavior:
``` javascript
// app.component.ts...
@ViewChild(DxSelectBoxComponent) selectBox: DxSelectBoxComponent;
  ngOnInit(){
    this.selectBox._collectionContainerImpl._setOption('allowClearing',false);
    console.log(this.selectBox);
  }
```
I wonder if there is an equivalent way to do this with a dxo child of the dx-select-box?
Thanks, Brian

**Comment by artem-kurchenko** [comment]
Hi,
 
As far as I understand, you need to assign a custom value on clearing the input. If so, DxSelectBox doesn't have a built-in option for this. You can define the onValueChanged handler to complete this task - http://plnkr.co/edit/B3WPSXqMuZeEUF6mNSuq?p=preview
 
Note that the issue is not specific to the angular integration package. If you need further assistance with this task, create a ticket in the DevExpress Support Center. Our support team will be happy to assist you.
