### ISSUE TITLE
Toolbar locateInMenu item multiple onClick call

### ISSUE THREAD

**Issue by ArtemAlekhin** [DevExpress/devextreme-angular#462]
devexteme version: 17.1.3
    devextreme-angular version: 17.1.3

Hi, I try to repeat the example (http://plnkr.co/edit/RLlReww1rmaz8VYWMZ70?p=preview). My markup looks like this:
`	<dx-toolbar>
		<dxi-item locateInMenu="always" text="Test" [onClick]="test()"></dxi-item>
	</dx-toolbar>`
In this case, the test() method is called many times. How can I properly declare locateInMenu item onClick  event?

**Comment by NikitaKunashov** [comment]
Since the onClick option is an event handler you need to use parentheses instead of square brackets as suggested in the [Event binding](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#event-binding) section of Angular tutorial. If you still experience the issue, you are welcome to fork our Plunker sample and update it to illustrate your scenario.
