### ISSUE TITLE
Use my own component inside dx-form

### ISSUE THREAD

**Issue by mickjol** [DevExpress/devextreme-angular#480]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.3
    devextreme-angular version: 17.1.3
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x ] support inquiry 

Actually I do this and it's work. But when I used my datasource "questions" in dx-tree-view the old selection of tree change with the value of my new selection.

`<dx-form [formData]="questions[selectedIndex]" (onFieldDataChanged)="onFormUpdated('form',$event)">
        <dxi-item [label]="{text: 'title' | translate}" dataField="title">
          <app-multilang [value]="questions[selectedIndex].title" (onValueChanged)="onFormUpdated('title',$event);"></app-multilang>
        </dxi-item>
</dx-form>`

Can I use the "dataField" of dxi-item directly with my component ?

**Comment by GoshaFighten** [comment]
If you need to provide a dxForm item with a custom editor, it's correct to use the item template. Since you use a custom template, you need to manually synchronize the template content with the dxForm bound form data. So, setting only the item `dataField` option is not sufficient to create a custom editor in the item template display and edit the correct value.
 
But, you mentioned that the issue occurs with dx-tree-view. I don't see dxTreeView in your code snippet. Provide me with a sample project that reproduces the issue so that I can give you a precise answer. You can create it from the sample [Plunker](http://plnkr.co/edit/XuAPDd?p=preview).

**Comment by mickjol** [comment]
[This is my plunker with my problem](http://plnkr.co/edit/DFWu6e?p=preview)

- You can select one question
- Modify the "description"
- Select a new question

When you select the second question the description of the first question on tree-view change to be the same of the second one.

**Comment by GoshaFighten** [comment]
The cause of the issue is that you are assigning the entire `_value` object coming from the `MultilangComponent` to the `description` field of the selected question in the `onFormUpdated` event handler. But, when a user selects another question, you don't re-create the `_value` object and you are changing fields of the existing options. So, new changes are applied everywhere the `_value` object is assigned. To resolve the issue, create a new ``_value` object in the `value` property setter method:
 
``` TypeScript
set value(val: object) {
this._value = {};
//
}
```
 
See the updated [Plunker](http://plnkr.co/edit/s0QIiYbmjKmsyyBg84Vw?p=preview).

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
