### ISSUE TITLE
How to import only one devextreme component in SystemJS

### ISSUE THREAD

**Issue by nachocoig** [DevExpress/devextreme-angular#571]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: **17.1.7**
    devextreme-angular version: **17.1.7**
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[**X**] support inquiry 

Hello!!! 

I'm trying use only one devextreme component using SystemJS, but it's impossible for me.

If i load all components, my Angular App takes a long time to load, and, i only need two or three components.

Any ideas?

Thanks!!!!

**Comment by wartab** [comment]
I have asked DevExtreme's support about this and I got the reply to build devextreme manually using SystemJS Builder.

Even if I do not think this is an acceptable answer, I still proceeded and did the following:

build-devextreme.js
```js
let Builder = require("systemjs-builder");

let builder = new Builder("", "src/systemjs.config.js");

builder
    .bundle("devextreme-angular/index.js", "./vendor/devextreme-build/index.js", {
        fetch: function (load, fetch) {
            if (load.name.match(/\.js$/)) {
                return fetch(load);
            }
            load.name+= ".js";
            load.address+= ".js";
            return fetch(load);
        },
        externals: ["devextreme/**/*"],
        globalDeps: {
            "jquery": "jQuery"
        }
    })
    .then(() => console.log("Build complete"))
    .catch(err => {
        console.error("Build failed");
        console.error(err);
    });
```

Now, you do not need to change anything in systemjs.config.js

Just include the newly generated Script after your SystemJS script import in your HTML.

```html
<script src="systemjs.config.js"></script>
<script src="../vendor/devextreme-build/index.js"></script>
```

**Comment by GoshaFighten** [comment]
For production, use the [SystemJS Builder tool](https://github.com/systemjs/builder) as @wartab described. It will build several modules into one bundle. So, you won't get hundreds requests for our modules, or others. But, since it takes some time to build a bundle, this approach may be slow for development. To load only necessary modules, use the approach provided in the [Bundlers without Tree Shaking Support](https://github.com/DevExpress/devextreme-angular#bundlers-without-tree-shaking-support) topic. So, import only those modules that are needed. For example, if you need only our button, import only its module:
 
``` TypeScript
import {DxButtonModule} from 'devextreme-angular/ui/button';
 
@NgModule({
imports: [ 
BrowserModule,
DxButtonModule
],
declarations: [ App ],
bootstrap: [ App ]
})
```
 
Make sure that you use long paths like `devextreme-angular/ui/button`, but not `devextreme-angular`. See the [plunk](http://plnkr.co/edit/GG0dixTUS8SEpT0HQA33?p=preview) that illustrates this.

**Comment by wartab** [comment]
I do not think it's a bad solution for development as you do not need to build the bundle constantly, once should suffice, especially if you only build Devextreme-Angular and Devextreme with this.

**Comment by GoshaFighten** [comment]
@wartab Feel free to use this approach if it meets your requirements.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by nachocoig** [comment]
Sorry for my inactivity. Thanks for your help! 

Regards

**Comment by GoshaFighten** [comment]
You are welcome, @nachocoig !
