### ISSUE TITLE
dx-switch placed in a grid cell doesn't fire the onValueChanged value when you drag the slider

### ISSUE THREAD

**Issue by elasticrash** [DevExpress/devextreme-angular#640]
devexteme version: 17.2
    devextreme-angular version: 17.2

[x] bug Report

reproduced issue http://plnkr.co/edit/b18kuw?p=preview

description 
I used a dx-switch inside a dx-grid 
when I click the dx-switch the onValueChanged gets fired as expected
but when you drag the switch (with the mouse) the onValueChanged doesn't get fired

**Comment by GoshaFighten** [comment]
Yes, I see this behavior. I can confirm that it is not reproducible with jQuery. See the [CodePen sample](https://codepen.io/anon/pen/KZdgay?editors=0011). This behavior may relate to #618. We will research this behavior. Stay tuned to our updates.

**Comment by GoshaFighten** [comment]
Thank you for your patience, @elasticrash. We researched this issue and its cause is that you are binding the dx-switch value to a grid data source field in two-way mode.  
The grid also tracks changes in its fields by default. 
So, when you swipe the dx-switch handler, this updates the grid's data source field via Angular binding first and then, the grid is refreshed. Refreshing the grid disposes of the dx-switch and onValueChanged is not raised. When you click the dx-switch, we update its value with a delay. So, the dx-switch raises its onValueChanged event first and then, the grid is refreshed.
 
To avoid the issue, I can suggest several approaches to you.
 
1. You can disable the grid's [twoWayBindingEnabled](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#twoWayBindingEnabled) option. In this case, the grid won't track changes in its data source automatically. See the [plunk](http://plnkr.co/edit/SwW1e4FCZM6kueCLgifA?p=preview) that illustrates this.
 
2. Don't use two-way binding for the dx-switch value option. Instead, update the grid's data source in the onValueChanged event handler. See the [plunk](http://plnkr.co/edit/mG5XQgoWQBRsWXC2iT6k?p=preview) that illustrates this.
 
3. You can use the grid's built-in [editing](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/) capability. For this, use the column's [editCellTemplate](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#editCellTemplate) rather than cellTemplate and set the column's [showEditorAlways](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#showEditorAlways) option to true to render the dx-switch in a column cell. In the dx-switch onValueChanged event handler, use the [setValue](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#editCellTemplate) method of the editCellTemplate parameter to update the corresponding grid data source value. See the [plunk](http://plnkr.co/edit/XEUpkLIJbxtpkLStzHi5?p=preview) that illustrates this.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
