### ISSUE TITLE
Can't bind to 'shrink' since it isn't a known property of 'dxi-item'.

### ISSUE THREAD

**Issue by alert83** [DevExpress/devextreme-angular#676]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

compiler.js:485 Uncaught Error: Template parse errors:
Can't bind to 'shrink' since it isn't a known property of 'dxi-item'.
1. If 'dxi-item' is an Angular component and it has 'shrink' input, then verify that it is part of this module.
2. If 'dxi-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    id="dx-box-item1"
    [ratio]="0"
    [ERROR ->][shrink]="0"
    [baseSize]="'auto'"
  >
")

**Comment by GoshaFighten** [comment]
This should work. Would you please modify the [plunk](https://plnkr.co/edit/oLe4EReKgtuHCrEynzwL?p=preview) to reproduce the issue?

**Comment by hakimio** [comment]
Have you imported the `DxBoxModule` module?

**Comment by alert83** [comment]
of course.  look at above: 
...
[ERROR ->][shrink]="0". 
...
error appeares only in front of shrink property.

**Comment by hakimio** [comment]
@alert83 If it works in Dmitry's example, but not in your code, most likely there is something wrong with your code...

**Comment by richie50** [comment]
i'm having that exact same issue. I'm following the guidelines exactly
Error: Template parse errors:
Can't bind to 'dataSource' since it isn't a known property of 'dx-scheduler'.
1. If 'dx-scheduler' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
2. If 'dx-scheduler' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by hakimio** [comment]
@richie50 Have you imported "DxSchedulerModule" to your Angular module?

**Comment by alert83** [comment]
It's work after deps have been updated

сб, 17 февр. 2018 г., 14:48 Tomas Rimkus <notifications@github.com>:
