### ISSUE TITLE
Trigger CustomStore update method in DataGrid

### ISSUE THREAD

**Issue by RomanNagornyi** [DevExpress/devextreme-angular#698]
devexteme version: 17.2.4
    devextreme-angular version: 17.2.5-beta.1

[ ] bug Report 
[x] feature request 
[ ] support inquiry 

Hello

Please help me to resolve my issue.

Is it possible to trigger update method in case when no data in dxo-editing section changed?
```javascript
<dx-data-grid [dataSource]="dataSource">
   <dxo-editing
       mode="form"
       [allowUpdating]="true"
       [allowDeleting]="true"
       [allowAdding]="true">
       <dxo-form>
           <dxi-item dataField="name" caption="Game name">
           </dxi-item>
           /// others fields
      </dxo-form>
   </dxo-editing> 
</dx-data-grid>
```

I have found some partial solution to implement this method
```javascript
  onRowUpdating(e) {
    for (var property in e.oldData) {
      if (!e.newData.hasOwnProperty(property)) {
        // add a non-existing value
        e.newData[property] = e.oldData[property];
      }
    }
  }
```

which helps to populate all data but isn't triggered too, but the question is how to trigger update method
```javascript
this.dataSource.store = new CustomStore({
    update: function (key, value) {        
         // I add here some additional data to POST
         // request to update
    }
});
```

Thanks for helping in advance!

**Comment by GoshaFighten** [comment]
It's not clear to me why you need to update a row if no changes have been made in it. Perhaps, you can just use the CustomStore [update](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/CustomStore/Methods/#updatekey_values) method to achieve the required behavior. But, I suggest you open a new [Support Center ticket](www.devexpress.com/ask) to describe your scenario in greater detail so that so we can provide you with a precise solution.
