### ISSUE TITLE
SelectedItem property in Lookup

### ISSUE THREAD

**Issue by Lindvorn** [DevExpress/devextreme-angular#699]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.5
    devextreme-angular version: 17.2.5
- Specify the type of the issue (check one with "x"):
[X] bug Report 
[ ] feature request 
[ ] support inquiry 

Greetings.
In the documentation for Lookup the SelectedItem property is specified. But it's missing in the dx-lookup when I try get it from event's 'component' property.
Now the only way to access this property is to use "component.options('selectedItem')"
Can you please, add this property to Lookup.

Thank you in advance.

**Comment by GoshaFighten** [comment]
You are getting the correct behavior. The `component` option in a component event references a DevExtreme widget instance rather than the DxLookup Angular component. It's correct to use the [option](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxSelectBox/Methods/#optionoptionName) method to obtain a DevExtreme widget option value. If you need to access our Angular component instance, you can do this using the Angular [ViewChild](https://angular.io/api/core/ViewChild) directive or by assigning a [template reference variable](https://angular.io/guide/template-syntax#template-reference-variables--var-) to an Angular component markup element as described in the [Accessing a DevExtreme Widget Instance](https://github.com/DevExpress/devextreme-angular#accessing-widget-instance).

``` HTML
<dx-lookup (onValueChanged)="onValueChanged($event)"></dx-lookup>
```
``` TypeScript
onValueChanged(e: any) {
  console.log(e.component.option("selectedItem"));
}
```

``` HTML
<dx-lookup #lookup (onValueChanged)="onValueChanged(lookup.selectedItem)"></dx-lookup>
```
``` TypeScript
onValueChanged(selectedItem: any) {
  console.log(selectedItem);
}
```
