### ISSUE TITLE
Update: function (key, values) - Only passes updated values?

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#736]
I might be utilizing this wrong but I would of thought when saving an updated row that the whole rows values would have been passed (similar to an insert?)

Its just when I try and update a value only the changed values are logged.

Is there a way to pass the complete object back with unchanged and changed values?

Example plnkr showing logging

https://plnkr.co/edit/JMTfJWLsz7pHzauhnAoM?p=preview

Code extract
```
          update: function (key, values) {
                console.log("THE KEY IS")
                console.log(key)
                console.log("THE VALUES ARE")
                console.log(values)
                return http.put('https://jsonplaceholder.typicode.com/posts/' + encodeURIComponent(key), values)

```

**Comment by GoshaFighten** [comment]
This questions relates to how our DevExtreme DataGrid works rather than to our Angular integration. So, please post such questions to our [support center](www.devexpress.com/ask).

Yes, you see the correct behavior. The update method gets only updated fields. You can get all row fields by using the approach described in the [MVC DataGrid - How to pass all model fields to an update (put) action](https://www.devexpress.com/Support/Center/Question/Details/T500089) ticket.
