### ISSUE TITLE
Add currency to dataType

### ISSUE THREAD

**Issue by JaviRpo** [DevExpress/devextreme-angular#745]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.7
    devextreme-angular version: 17.2.7
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[x] feature request 
[ ] support inquiry 

https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#dataType

**Comment by GoshaFighten** [comment]
This questions relates to how our DevExtreme DataGrid works rather than to our Angular integration. So, please post such questions to our [support center](www.devexpress.com/ask).

Currency columns are number columns with corresponding formatting. So, set the column's [format](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#format) option to "currency" to achieve the required functionality.
