### ISSUE TITLE
Issue with multiple selection

### ISSUE THREAD

**Issue by shanmugam-siva** [DevExpress/devextreme-angular#760]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 16.2.5
    devextreme-angular version: 16.2.5
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[] support inquiry 

Issue with multiple selection

I have a  multi selection enabled grid which has around 1000 records without pagination. I selected the first record, scrolled down to end of the grid and selected the last record (ctrl + shift + mouseclick) to select all records in the grid. But when I scroll up only few records are selected.
Rows from 1 - 960 are not selected and rest of the rows are selected. The same functionality works fine when the grid has 100 odd rows.

Here is the HTML 

<dx-data-grid class="tradeGridHeight display-full-height"
        noDataText='No data available'
        showColumnLines="true"
        showRowLines="true"
        rowAlternationEnabled="true"
        showBorders="true"
        remoteOperations="false"
        allowColumnResizing="true"
         [filterRow]="{
            visible: true,
            applyFilter: 'auto'
        }"
        [sorting]="{
            mode: 'multiple'
        }"
        [selection]="{
            mode: 'multiple',
            showCheckBoxesMode: 'none'
        }"
        [loadPanel]="{
            enabled: false
        }"
        [dataSource]="{ store: arrayStore }"
        [paging]="{
            pageSize: 30
        }"
        [scrolling]="{
            mode: 'virtual',
            useNative: true,
            preloadEnabled: true
        }">

**Comment by GoshaFighten** [comment]
The grid selects its rows by their key. So, your store should have the key option specified. Otherwise, the entire row is considered as the key. Since you didn't provide what your arrayStore looks like, I can't determine this precisely. First, you specified 16.2.5 as your current version. We made a lot of improvements since this version in the grid regarding selection. I suggest you update to the latest (17.2.7) to see how it works. If the issue is still reproducible, please submit a support request to our [support center](www.devexpress.com/ask) along with a sample project that reproduces the issue. We will research it to provide you with an accurate answer.
