### ISSUE TITLE
Custom dx-toast is not working correctly

### ISSUE THREAD

**Issue by ErBhautik** [DevExpress/devextreme-angular#782]
I want to customize height, width, and location of dev extreme toast in an angular way.

<dx-toast message='Toast message' [displayTime]='5000000' type="error" [(visible)]="isToastVisible" [position]="{
        my: 'right',
        at: 'top',
        of: window, 
        offset: '0 0'
      }"></dx-toast>

I have also try notify("text","type","displaytime") method.

**Comment by GoshaFighten** [comment]
Hi @ErBhautik,
 
Would you please elaborate on what behavior you have now and what behavior you expect?

**Comment by ErBhautik** [comment]
Hi @GoshaFighten
DevExtreme toast working fine with default Type("Sucess" || "error" || "info") with default behaviour.But as per the documentation if we use type="custom" then we can apply our custom CSS class ".dx toast custom" which is not working properly.

Expected behavior : I want to use custom toast type and apply custom CSS.

**Comment by GoshaFighten** [comment]
I think that your custom CSS rules are not applied to the Toast because you don't prefix their selectors with [/deep/ or ::ng-deep combinators](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep). So, your styles should look like:

```CSS
::ng-deep .dx-toast-custom {
    background-color: green
}
```

If this is not the case, provide me with a sample project to reproduce the issue.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive.
