### ISSUE TITLE
Transparent background on Safari

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#895]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version: 18.1.6
    devextreme-angular version: 18.1.6
- Specify the type of the issue (check one with "x"):
[X] bug Report 

Background of tooltips and chart disappear on hover on Safari (mac os 10.14).

Just created a very simple application (ng new and added DevExtreme manually).

This is the result: [link](https://imgur.com/a/SAiWdDt)

But when I put the mouse over the chart I get this result: [link](https://imgur.com/a/tNVmffg) (the chart disappear).

At [this link](https://ufile.io/b3tpl) you can find the zip containing the project.

Thank you

**Comment by sometimesElen** [comment]
I tried to reproduce the issue locally but did not succeed. In your sample, I see that you create a Chart inside the <base> tag. In this case, I suggest you enable the [pathModified](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/#pathModified) option. 

If you enabled the pathModified option and the issue is still reproduced and you wish to continue discussing this issue, I suggest you [create a ticket](https://www.devexpress.com/Support/Center/Question/Create) in our Support Center. Our support engineers are always ready to help with any DevExpress product.
