### ISSUE TITLE
[18.2] Filter Row for dataType="Date" returns wrong operator

### ISSUE THREAD

**Issue by brunoccsnasajon** [DevExpress/devextreme-angular#936]
I'm trying to implement a custom implemetation of the filters on the back end, using loadOptions.Filter. When a column has dataType="Date", the filter returned to loadOptions is not the same selected by the user, ex.: equals becomes between, LessThan becomes GreaterOrEqualsTo, etc...

**Comment by AlexanderKovalenko** [comment]
Hi,

This is the expected behavior. The resulting filter expression is generated so that fractional dates are present in the filtered set. For example, if you select date = 2019/1/1, then all dates with non-zero time (2019/1/1 10:00:00) will be displayed.
 
If you need to customize the filter expression, modify it according to your requirements.
 
See also: [A custom data source does not apply paging, filtering, sorting and grouping](https://www.devexpress.com/Support/Center/Question/Details/KA18955/a-custom-data-source-does-not-apply-paging-filtering-sorting-and-grouping)
