### ISSUE TITLE
Problem with ng test where app does have a dependency to devextreme-angular

### ISSUE THREAD

**Issue by agerbig** [DevExpress/devextreme-angular#978]
# Bug Report
I migrated an angular 7 project to angular 8. The application runs and npm test works but ng test does not work.
‍
The project needs the devextreme-angular component.
Any ideas how to get it working?

**Package versions:**
    @angular/core: ~8.1.1
    devexteme version: ^19.1.4
    devextreme-angular version: ^19.1.4

**Steps to reproduce:**

I created a simple angular 8 application with the same setup. Then I added the dependencies step by step to the package.json. After each new dependency I deleted the node_modules folder and the package-lock.json file. The problem appears when the dependency to devextreme-angular was added.
The sample project is hosted at GitHub (https://github.com/agerbig/angular8-jest-devextreme).
The problem is this dependency:
```
"dependencies": {
    ...
    "devextreme-angular": "^19.1.4",
    ...
  },
```

**Current behavior:**

If you build the project with npm install and execute the tests with ng test the following error occurs:
```
An unhandled exception occurred: core_1.experimental.workspace.Workspace.fromPath is not a function
```
When you remove the dependency to devextreme-angular and execute the following commands the tests are successfully executed:
```
‍rm -rf node_modules
‍rm package-lock.json
‍npm install
‍ng test
```

**Expected behavior:**

The command ng test would execute the tests similar to npm test.

**Comment by LexDX** [comment]
Hi,
 
I reproduced the issue using your project. Then, I created a brand new application, added Jest according to their documentation, and registered our DevExtreme-Angular package. Then, I tried the ng test command again, and it worked fine. This means that the issue is more related to the project configuration than to our package. 
 
Your note about removing and reinstalling the node_modules folder and the package-lock.json file gave me an idea. When you remove the package-lock file, all the dependencies are recreated from scratch by npm on the next install. So, it is possible that some of the dependencies were resolved/restored incorrectly.
 
I tested my sample and received the same error as in your sample. Then, I installed and tried the other package manager - yarn. I restored the node modules by using it, and tests in my project started to work again. So, I tested it in your project, and yarn resolved the issue in it too.
 
So, taking the above information into account, I recommend you use yarn in your project to avoid the initial error.
